### ISSUE TITLE
How to upload artifacts

### ISSUE THREAD

**Issue by markbeierl** [RedHatQE/openstack-gitlab-executor#4]
When using the artifacts clause in gitlab-ci.yml, the job gives the following message:

> Missing gitlab-runner. Uploading artifacts is disabled.

Is there any method to preserve artifacts created on the remote VM before it is terminated?

**Comment by quarckster** [comment]
The instance must contain `gitlab-runner` binary to upload artifacts. I use `virt-customize` utility to create a custom Openstack image with the required software:
```
virt-customize -v -a Fedora-Cloud-Base-34-1.2.x86_64.qcow2 --commands-from-file command_list.txt

cat command_list.txt
install git-core,git-lfs,podman,buildah,skopeo
copy-in /home/fedora/gitlab-runner:/usr/bin/
chmod 0755:/usr/bin/gitlab-runner
selinux-relabel
```

**Comment by quarckster** [comment]
https://docs.gitlab.com/runner/executors/custom.html#prerequisite-software-for-running-a-job
