### ISSUE TITLE
download gitlab-runner instead of building it

### ISSUE THREAD

**Issue by DEvil0000** [RedHatQE/openstack-gitlab-executor#8]
It may be way faster to download gitlab-runner instead of building it. This however is mostly style and build time optimisation.
Have a look at my ubuntu based variation of [Dockerfile](https://github.com/wingcon/openstack-gitlab-executor/blob/master/Dockerfile).
Not sure if you want to do this similar or if there is a prebuild version for redhat.

edit:
Also you may consider a ubuntu or alpine based dockerfile as well ;)
And many thanks for your version - i would have built the exactly same thing again

**Comment by quarckster** [comment]
> It may be way faster to download gitlab-runner instead of building it.

Yeah, the building takes some time but anyway you don't build it often.

> Also you may consider a ubuntu or alpine based dockerfile as well 
I made it for Red Hat and we have our own base distro.

**Comment by DEvil0000** [comment]
Thats the answer I expected. Thanks anyway, closing this then.
